### ISSUE TITLE
Prioritizing features in the project

### ISSUE THREAD

**Issue by PetervB** [alex9311/Information-Retrieval#37]
Hi,

I wanted to discuss the scope of our current project because what we want to do now is still too big for the amount of time we have left.

I think it is best to analyse the requirements of the course and make sure we fit those.

The things I think we should prioritize on:

Crowdsourcing: integration with crowd flower for idea sanitation check (create tasks)
IR: Similarity check
Show an overview of the top 5

The things we shouldn't focus on (because they are not relevant for the course):

Sign in & log in
Creation of user profiles
The "swiping" functionality (like buttons are just fine for starters)
Sharing

Please add to these lists the things I missed (probably a lot)

Peter

**Comment by millenniumproof** [comment]
According to my schedule, given the number of credits we get, I still have 70 hours to spend on the course. The integration with CrowdFlower won't take much time. And showing the top 5 can be done quickly as well. I believe presentation and usability to also be important to Information Retrieval. Especially since we don't have much else for incentivicing users. Prioritizing things is fine, but I do think we can make everything we set out to in the requirements.

**Comment by PetervB** [comment]
We also have an individual assignment that's going to take quite some time. And don't underestimate the time these things can take.

In my experience these "simple" things can take up to a week if you're new to the system, and we're not experienced with these systems...

**Comment by alex9311** [comment]
:thumbsup: upvote for not underestimating complexity, always my first rule!

Its important to prioritize the critical parts, and we can always do more features if we have time :neckbeard:
