### ISSUE TITLE
Building a Test set

### ISSUE THREAD

**Issue by millenniumproof** [alex9311/Information-Retrieval#50]
I figured we'd do this after we implemented the login, but since that's on the back-log (bag-log? :P) we might as well do it now to fill our idea box a bit. We'll use this data to test the precision and recall of the similarity check. 

Write a description in your own words for the following apps (all apps from google play):
Angry Birds
Snapchat
Zombies, Run!
Geocaching
Netflix
Crazy Helium Video Booth
Tinder
Collage Maker Pro
Magic Piano by Smule
Emoji Keyboard Pro

Change the title as well!
Link to submit page: https://docs.google.com/spreadsheets/d/1LgjjJAeTW6vX-9g2AnbhN-OPkmHgguABmH4KIFT__mI/

**Comment by alex9311** [comment]
hang on shouldn't we put these in a script rather than submitting them directly? That way we can reset and repopulate more easily.

I'm happy to write it if I have a list of descriptions and titles

**Comment by millenniumproof** [comment]
We can easily download a csv of the data after submitting directly. The idea was that we each write a description in our own words of each title so that we have differently worded descriptions of the same idea. The similarity check should be able to recognize the similarity in the descriptions. Knowing beforehand which data is relevant to the query, we can get concrete values for the evaluation.

**Comment by alex9311** [comment]
Yeah I agree that its a great idea and we definitely need it! 

I think it will be less error prone if each of us makes a CSV with the app descriptions and titles (or make a google spreadsheet for all of us and export it to csv). We could then import that into the DB afterwards (and reimport if necessary). I say this mostly because there are still some issues with the submit page:
- The char size limits (as defined in the DB) are probably wrong on title and description, possibly cutting off the ends of our submissions' titles and descriptions
- We would **have** to submit pictures with the ideas if we used the submit page, which would take time and is not needed if we want to use the test set for text similarity
- I might still test images and upload random ideas through the submit page over the next few days which would pollute our dataset

**Comment by millenniumproof** [comment]
Okay, I'll make a google spreadsheet then. I can write a script to write the csv to the database.
Adding an image to an idea shouldn't be compulsory, I think.

Link to submit page: https://docs.google.com/spreadsheets/d/1LgjjJAeTW6vX-9g2AnbhN-OPkmHgguABmH4KIFT__mI/

**Comment by HDking** [comment]
I filed it in!

**Comment by alex9311** [comment]
Hey @PetervB I think you're the last person that needs to fill this in still :neckbeard:
